### ISSUE TITLE
POST /users - Erro 500

### ISSUE THREAD

**Issue by dsalexan** [CodelabUnifesp/PlaSMeDIS-API#28]
## Contexto & Ambiente

DEV — http://plasmedis-api-dev.herokuapp.com
Rota POST /users

## Comportamento Esperado

POST /users, com o corpo formatado para JSON, deveria inserir o novo usuário no banco E retornar um sucesso.

## Comportamento Atual

POST /users está inserindo o usuário no banco (apesar de estar **ignorando** o email, sempre salvando o campo vazio no db), porém retorna status code 500 ao final.

## Possível Solução

Olhei o código por cima, não tenho certeza do que possa ser. **Talvez** seja algo com o formato do que ta indo no json vs o que o banco espera, mas se for isso não consegui identificar o porque (e se for a gente tem que mudar na api para aceitar).

## Passos para Reproduzir

![api_error_post_users](https://user-images.githubusercontent.com/12667933/126067329-424b528c-541b-42a3-96ed-959109634637.gif)

**Comment by Maegima** [comment]
@dsalexan verifiquei e acho que corrigi isso na pr #27, o endpoint POST /users estava usando o email sem verificar se ele existe, troquei pra ele usar o user_name ao envés do email e coloquei pra ele adicionar o email caso ele seja enviado no json. Não consegui reproduzir o seu erro em DEV.

Testei com e sem email especificado usando o banco de DEV.
### Sem email:
`curl -X POST -H "Content-type: application/json" 127.0.0.1:8000/users -d'{"user_name":"JohnDoe", "real_name": "John Doe", "password":"DoeJohn", "user_type": 1, "bairro": 1}'`

### Com email:
`curl -X POST -H "Content-type: application/json" 127.0.0.1:8000/users -d'{"user_name":"JohnDoe2", "real_name": "John Doe", "password":"DoeJohn", "user_type": 1, "bairro": 1, "email": "john@doe.com"}'`

**Comment by Maegima** [comment]
Acho que outro ponto da documentação e refatoração dos endpoints seria identificar e documentar os campos required e optional dos endpoints e também o tratamento de erro nos endpoints, além disso fazer o endpoint retornar um código html que faça sentido quando ocorrer algum erro ex.: 400 se o usuário enviar json faltando campo required.
