### ISSUE TITLE
Painel de configuracao de notificacoes

### ISSUE THREAD

**Issue by MMagueta** [CodelabUnifesp/PlaSMeDIS-API#3]
### Contexto

Para receber notificacoes customizadas, o usuario deve poder se inscrever em categorias de notificacao

### O que deve ser feito:

Um endpoint onde o usuario pode atualizar as suas configuracoes (PUT)

Tipos:
- [ ] Sistema
- [ ] Selo em postagem
- [ ] Comentário em postagem
- [ ] Nova postagem em categoria escolhida (saúde, lazer, trocas, etc)

**Comment by matheusac18** [comment]
Gostaria de trabalhar nessa
