### ISSUE TITLE
GET /postagens — Enviar comentários de cada postagem

### ISSUE THREAD

**Issue by dsalexan** [CodelabUnifesp/PlaSMeDIS-API#33]
Junto de cada postagem, enviar também um array com os comentários vínculados a postagem.
Idealmente esse array deve conter dados como: 

- id do comentário
- id do criador do comentario
- nome do criador do comentario
- data de criacao do comentario
- corpo do comentário.

![image](https://user-images.githubusercontent.com/12667933/126233200-d6b70a88-cd39-4b47-b6e9-293b70b8981f.png)

**Comment by Maegima** [comment]
@dsalexan será que não vale apena pra essa criar, um endpoint GET postagens/:id que retorna as informações desse única postagem com os comentários;
Outra coisa que eu pensei agora pra colocar na refatoração é criar um modelo de paginação pros endpoints que retornam listas.

**Comment by Maegima** [comment]
Outra coisa que eu pensei agora pra colocar na refatoração é criar um modelo de paginação pros endpoints que retornam listas.

**Comment by dsalexan** [comment]
> @dsalexan será que não vale apena pra essa criar, um endpoint GET /postagem/:id (ou mudar postagens/:id pra /postagens/categoria/id e fazer esse ser /postagens/:id) que retorna as informações desse única postagem com os comentários;

Seria o ideal, sem dúvidas. Não vejo problema, é só que o pooling das postagens é uma das tarefas futuras e (imagino eu) vai gerar mudanças consideráveis em qualquer coisa que envolva postagem (então qualquer coisa que seja feita agora pode ir pro limbo depois). Mas é a gosto do dev, sinceramente 

quanto a paginação, uma boa também, navega em águas parecidas com a do pooling
